### ISSUE TITLE
[Web] 메인 화면 - 메인 화면 구축

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#10]
[Web] 메인 화면 - 메인 화면 구축

**Comment by byepingu** [comment]
- [x] 메인화면 기능상 구축 완료

- 헤더 상단 왼쪽 로고 구현 (메인페이지 linked)
- 헤더 상단 오른쪽 마이페이지, 로그아웃 버튼 구현
- 메인 상단 "{회원별명. 없을시 회원아이디} 안녕하세요!" 타임리프로 구현
- 메인 하단 2개 서비스 선택 버튼 구현 (식단관리 서비스 or 식당검색 서비스)
- 풋터 개발팀이름
