### ISSUE TITLE
[Web] 지도 기능 - GPS(현재위치)

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#13]
[Web] 지도 기능 - GPS(현재위치)

**Comment by dayeah512** [comment]
현재 실시간 위치  마커로 찍어주는 상태까지 구현 하였으나 5초마다 업데이트 되어 마커가 수십개 생김 
-> 새로고침 하여 현재 위치 하나의 마커만 찍어주는 형태로 재수정 할 예정...

**Comment by hyul77** [comment]
5초마다 업데이트 삭제 완료
