### ISSUE TITLE
[Web] 지도 기능 - 검색창

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#14]
[Web] 지도 기능 - 검색창

**Comment by dayeah512** [comment]
구축 예정

**Comment by dayeah512** [comment]
구축완

**Comment by byepingu** [comment]
- [x] MySQL DB - MdStore, MdReview 엔티티 - 각 Repository - MdStoreService - MdMapController 구축
- [x] findAllByStoreName, findReviewsByReview 메소드 통해 DB로부터 검색어에 대한 검색(SQL select) 결과 제공
- [ ] 검색 결과: 검색어 하이라이트 기능
- [ ] 검색 결과 고도화

**Comment by bbundnam** [comment]
검색 키워드 띄어쓰기 경고 알림침 구축, 검색결과 건수 안내문 구축

**Comment by hyul77** [comment]
건수 확인, DB 연결
