### ISSUE TITLE
[Web] 지도 기능 - 필터 기능

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#16]
[Web] 지도 기능 - 필터 기능

**Comment by dayeah512** [comment]
카테고리화하여 웹에 보여주기까지 완료(추후 css예정)

**Comment by hyul77** [comment]
현재 영업 중인 -> 영업 시간으로 필터
예약 가능한 -> catch table에서 가져오든 booking으로 필터

**Comment by dayeah512** [comment]
<필터 예시 >맛있는, 깔끔한,청결, 예약가능, 회식, 혼밥, 데이트, 가족모임, 단체석,룸,프라이빗,주차, 콜키지프리,
반려동물, 새로오픈, 전통, 배달, 포장, 24시, 연중무휴

**Comment by bbundnam** [comment]
카테고리 별로 필터기능의 버튼의 클릭시 CSS 스타일유지 구현
