### ISSUE TITLE
[Web]  식단 밀땅일지 화면 - 식단 밀땅일지 화면 구축

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#19]
[Web]  식단 밀땅일지 화면 - 식단 밀땅일지 화면 구축

**Comment by byepingu** [comment]
- [x] 헤더(메뉴 이동, 로그아웃 등) 기능 및 기본 CSS 구현
- [x] 풋터 mock-up
- [x] 주간 AI 리포트 버튼 구현
- [x] 이미지 AI 분석 버튼 구현
- [ ] 식단DB 연결
- [ ] 테이블 구현

**Comment by dayeah512** [comment]
주간ai 리포트 막대 ,원, 영양수치 그래프 (js)구현 완료
