### ISSUE TITLE
[Web]  식단 밀땅일지 화면 - 이미지 AI 분석 화면 구축

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#20]
[Web]  식단 밀땅일지 화면 - 이미지 AI 분석 화면 구축

**Comment by byepingu** [comment]
- [x] 헤더(메뉴 이동, 로그아웃 등) 기능 및 기본 CSS 구현
- [x] 풋터 mock-up
- [x] 이미지 업로더 구현
- [x] 이미지 불러오기 구현
- [ ] 저장 버튼 구현
- [x] 모델API 연동
- [x] 식단영양정보DB 연동
- [x] 영양정보 테이블 시각화
- [x] 추가 디자인 업데이트

**Comment by byepingu** [comment]
이미지 불러오기 이슈: 아래 코드에서 이미지 찾아오지 못하는 문제
`<img th:if="${mdGallery != null}" th:src="@{'/'+${mdGallery.storedFileName}}" alt="uploaded">`
mdGallery.storedFileName = "static/images/..."

아래 코드는 잘 작동함. 즉, src = "/static/..." 경로는 맞음.
`<img th:unless="${mdGallery != null}" src="/static/icons/plate.png" alt="default">`

엑박 이미지 소스 링크를 확인한 결과, localhost:8080/static/... 으로, 의도한 주소가 맞음.
이미지 잘 불러오는 링크 역시 localhost:8080/static/... 형식이 맞음.

원인이 무엇일지 ...

**Comment by byepingu** [comment]
원인은 <서버 재가동>

[정적 리소스 경로 설정해주기, 로컬에 저장된 업로드 이미지가 서버 재시작해야만 반영되는 문제](https://g4daclom.tistory.com/77)

위 사이트 참고해서 addResourceHandlers 설정을 추가했지만 여전히 해결되지 않음.

**Comment by byepingu** [comment]
저장 버튼을 삭제 버튼으로 바꿀 예정 (디폴트가 저장임)
