### ISSUE TITLE
[Web]  식단 밀땅일지 화면 - 주간 AI 리포트 화면 구축

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#21]
[Web]  식단 밀땅일지 화면 - 주간 AI 리포트 화면 구축

**Comment by byepingu** [comment]
- [x] 헤더(메뉴 이동, 로그아웃 등) 기능 및 기본 CSS 구현
- [x] 풋터 mock-up

**Comment by dayeah512** [comment]
주간ai 리포트  그래프 (js)시각화 구현 완료

**Comment by byepingu** [comment]
화면 mock-up 완료. 상세 기능은 별도 이슈로 관리하겠음.
