### ISSUE TITLE
[Web]  마이페이지 화면 - 마이페이지 화면 구축

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#22]
[Web]  마이페이지 화면 - 마이페이지 화면 구축

**Comment by byepingu** [comment]
- [x] 헤더(메뉴 이동, 로그아웃 등) 기능 및 기본 CSS 구현
- [x] 풋터 mock-up
- [x] 메인섹션 mock-up
- [x] 메인섹션 기능 구현
- [ ] 추가 디자인 적용?
