### ISSUE TITLE
[Web] 주간 AI 리포트 화면 - 차트 기능

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#25]
[Web] 주간 AI 리포트 화면 - 차트 기능

**Comment by dayeah512** [comment]
기본 그래프 구현 완료 (밀땅에 맞는 그래프 찾아 구현 예정)

**Comment by dayeah512** [comment]
<일일섭취량 > 구현완료
<권장영양섭취비율-원그래프> 구현완료
<신호등> 구현 진행 중 밀땅에 맞는 그래프 구하지 못해 하드 코딩중...

**Comment by dayeah512** [comment]
<신호등> 구현 완료

**Comment by dayeah512** [comment]
입력데이터에 따른 시각화 구현 예정
