### ISSUE TITLE
[Web] 마이페이지 화면 - 개인정보 수정 기능

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#26]
[Web] 마이페이지 화면 - 개인정보 수정 기능

**Comment by byepingu** [comment]
- 헤더(메뉴 이동, 로그아웃 등) 기능 및 기본 CSS 구현
- 풋터 mock-up

**Comment by byepingu** [comment]
회원가입 단계에서는 최소한의 정보(로그인용 아이디, 비밀번호, 이메일)만 요구합니다. 회원가입 단계가 복잡하면 회원유치에 도움이 되지 않기 때문입니다.
식단관리를 위해서 필요한 부가 정보는 마이페이지에서 수정이 가능합니다.

**Comment by byepingu** [comment]
- [x] 별명
- [x] 생일 
- [x] 성별 
- [x] 키
- [x] 몸무게

**Comment by byepingu** [comment]
기능 이슈 : 기존 성별이 '여성'일 때 기존 정보대로 체크가 안 되어 있는 문제
(별명 등 다른 정보는 기존 정보가 디폴트로 적용되어 있음)

**Comment by byepingu** [comment]
성별 체크 기능 이슈 해결
`<input type="radio" id="gender" name="gender" value="F" th:checked="${mdUser.gender == null and mdUser.gender != 'M'}" required/>여성
<input type="radio" id="gender" name="gender" value="M" th:checked="${mdUser.gender != null and mdUser.gender == 'M' }" required/>남성`
기존 코드: null 여부에만 초점을 두고 작성됨

`<input type="radio" id="gender" name="gender" value="F" th:checked="${mdUser.gender == 'F' || mdUser.gender == null}" required/>여성
<input type="radio" id="gender" name="gender" value="M" th:checked="${mdUser.gender == 'M'}" required/>남성`
수정 코드: null 여부와 기존 값을 모두 고려하여 작성

**Comment by bbundnam** [comment]
개인정보 CSS 적용
출생년도 드롭다운 셀렉트 적용
