### ISSUE TITLE
[Web] 마이페이지 화면 - 음식 갤러리 기능

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#27]
[Web] 마이페이지 화면 - 음식 갤러리 기능

**Comment by byepingu** [comment]
- [x] 헤더(메뉴 이동, 로그아웃 등) 기능 및 기본 CSS 구현
- [x] 풋터 mock-up
- [x] 갤러리 엔티티 ~ 컨트롤러 구축
- [ ] 회원용 갤러리 보드 구축
