### ISSUE TITLE
[DB] 회원 Table - 회원 Table 설계

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#28]
[DB] 회원 Table - 회원 Table 설계

**Comment by byepingu** [comment]
완료!

**Comment by byepingu** [comment]
User Table 설계 완료
- 자바 스프링부트 mysql connector, jpa dependencies 통해 DB 연결
- 자바 스프링부트 Entity, Table, Column, Id 등 어노테이션 통해 DB테이블 생성
- 회원아이디, 회원비밀번호, 이메일, 닉네임, 성별, 생년월일, 신장, 체중 컬럼
