### ISSUE TITLE
[DB] 음식점 정보 Table - 음식점 정보 Table 설계

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#29]
[DB] 음식점 정보 Table - 음식점 정보 Table 설계

**Comment by byepingu** [comment]
저는 ERD 설계 초안 작성했습니다. 음식점 정보 수집 담당해주신 분들께서 업뎃해주세요!

**Comment by hyul77** [comment]
초안 작성 완료, 식당 통합 완료
