### ISSUE TITLE
[Crawling] 카카오 - 식당 리뷰, 음식점 메뉴, 사진

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#50]
[Crawling] 카카오 - 식당 리뷰, 음식점 메뉴, 사진

**Comment by DaSeul-Seo** [comment]
0. 사용 기술
- Python
- Selenium
- BeautifulSoup
- request

1. 식당정보
- 식당 ID
- 식당 명
- 전호번호
- 주소
- 홈페이지
- 카테고리
- 영업시간
- 예약 가능 여부
- 포장 가능 여부
- 배달 가능 여부
- wifi 여부
- 반려동물 가능 여부
- 주차 여부
- 휠체어 사용 여부
- 식당 평점
- 식당 메뉴
- 식당 선호도
   - 성별, 나이대
- 리뷰 태그

2. 리뷰 정보
- 유저명
- 별점
- 리뷰
- 리뷰 작성일
- 태그
- 리뷰 사진
