### ISSUE TITLE
[Model] 음식 분류 Model - 음식 분류 Model List 추출

### ISSUE THREAD

**Issue by DaSeul-Seo** [Port8090/Store_Wiki#62]
[Model] 음식 분류 Model - 음식 분류 Model List 추출

**Comment by DaSeul-Seo** [comment]
1. SOTA (State-of-the-Art)에서 Object Detection 모델 리스트 확인
2. Backbone별 적어도 1개로 모델 리스트 추출
3. 최대 10개 모델 리스트 추출해서 비교

**Comment by hyul77** [comment]
Yolo V8
Yolo V5 
Yolo V3
환경설정
