### ISSUE TITLE
[Review] Review 분석 - 리뷰 분석 관련 아이디어 기록

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#64]
[Review] Review 분석 - 리뷰 분석 관련 아이디어 기록

**Comment by hyul77** [comment]
리뷰 분석을 할 때 1차적으로 유무만 존재 확인을 할 수 있음.
또한 감성분석을 할 때 옳게 했는지 안했는지 확인 할 방법이 없음 (라벨이 없음)
네이버 리뷰에서 데이터를 추출할 때, 네이버에서 제공하는 키워드로 해당 리뷰의 라벨을 결정하여 학습을 할 수 있음.

키워드 추출로 벡터 값을 계산해 해당 라벨의 값이 맞는지 체크할지 더 고민을 해야함.

**Comment by hyul77** [comment]
https://github.com/seonwoojh/Datapipeline_Project
쇼핑몰 리뷰를 활용한 NLP 감성분석 파이프라인 프로젝트

RNN의 한 종류인 GRU를 활용함

**Comment by hyul77** [comment]
https://www.dbpia.co.kr/pdf/pdfView.do?nodeId=NODE10534986
텍스트마이닝 기법과 ARIMA 모형을 활용한 배달의 민족 앱 리뷰 분석

**Comment by hyul77** [comment]
https://github.com/krisuety/Mango_plate_NLP
식당 리뷰를 보고 웨이팅, 가성비, 서비스 세가지 항목에 대해 감성분석

**Comment by hyul77** [comment]
https://github.com/SKT-AI/KoGPT2
KoGPT2 (한국어 GPT-2) Ver 2.0

**Comment by hyul77** [comment]
https://github.com/krisuety/Mango_plate_NLP/blob/master/model/machine_learning/mangoplate_ml.ipynb
망고플레이트 맛집 리뷰 감성분석 (머신러닝)

**Comment by hyul77** [comment]
https://github.com/Suyeon0709/MovieTomatoes/blob/main/AI/ModelLearning.py
[학습된 AI모델을 활용해서 긍부정 분석 완료]

**Comment by hyul77** [comment]
https://github.com/LIMDANBI/sentimentAnalysis
CNN을 이용한 감성분석 (Movie Reviews)

**Comment by hyul77** [comment]
https://yuddomack.tistory.com/entry/%EC%B2%98%EC%9D%8C%EB%B6%80%ED%84%B0-%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94-EC2-konlpy-mecab-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0ubuntu

**Comment by hyul77** [comment]
https://github.com/YeoHangJiSsokSsok/YHJSS-backend
여행지 쏙쏙 : 감성분석 기반 여행지 리뷰 요약 시스템

**Comment by hyul77** [comment]
https://github.com/SeoJeongYeop/ABSA-web-empath
2023 성균관대학교 소프트웨어학과 졸업작품 - 웹 수집 데이터 속성기반 감성분석 웹 애플리케이션

**Comment by hyul77** [comment]
https://bbarry-lee.github.io/ai-tech/KoBERT%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-%EA%B0%90%EC%A0%95%EB%B6%84%EB%A5%98-%EB%AA%A8%EB%8D%B8-%EA%B5%AC%ED%98%84.html
KoBERT를 활용한 감정분류 모델 구현 with Colab

**Comment by hyul77** [comment]
https://coding-yesung.tistory.com/201
워드클라우드

**Comment by byepingu** [comment]
https://github.com/yejoon-lee/kr3/tree/master
음식점 리뷰 감성분석 참고자료

**Comment by hyul77** [comment]
'nouns', 'adjectives'

predict_review.ipynb
stopwords.pkl
tokenizer.pkl
final_model_v0.h5
tokenized_data.csv

정확도 : 0.8847034140759107

'verbs', 'adjectives'

predict_review_VA.ipynb
stopwords_VA.pkl
tokenizer_VA.pkl
final_model_VA.h5
tokenized_data_VA.csv
정확도 : 0.5077395722557013


'nouns', 'adjectives', 'verbs', 'exclamations'
predict_review_ALL.ipynb
stopwords_ALL.pkl
tokenizer_ALL.pkl
final_model_ALL.h5
tokenized_data_ALL.csv
정확도: 0.966268862806983

berf_classifier.ipynb
정확도 : 0.9682
