### ISSUE TITLE
[Web] 로그인 화면 - 로그인 화면 구축

### ISSUE THREAD

**Issue by hyul77** [Port8090/Store_Wiki#8]
[Web] 로그인 화면 - 로그인 화면 구축

**Comment by byepingu** [comment]
디자인은 없고 기능만 구현되는 수준으로 화면 구축했습니다.

**Comment by byepingu** [comment]
- [x] 헤더(linked logo) 기능 및 기본 CSS 구현
- [x] 풋터 mock-up
